import {ItemType, PropertyType} from "@interfaces/GameInterface.ts";
import {GangMemberRoles} from "@interfaces/GangInterface.ts";
import {TicketStatus} from "@interfaces/UserInterface";
import {BetStatus} from "@screens/property_details/Casino/Blackjack.tsx";
import LocalizedStrings from "localized-strings";

let strings = new LocalizedStrings({
    en: {
        groupFight: {
            dealtDmg: "Dealt DMG",
            takenDmg: "Taken DMG",
            joinFight: "Join Fight",
            crewSize: "Crew",
        },
        inventory: {
            addToFavorite: "Add to Fav",
            removeFromFavorite: "Remove from Fav",
            favorites: "Favorites",
        },
        guards: {
            resetStatistics: "Reset Statistics",
            resetStatisticsDescription:
                "Resetting statistics will reset all your guard's statistics, are you sure?",
            title: "Guards",
            myGuards: "My Guards",
            hire: "Hire",
            salary: "Salary",
            selectJob: "Select Solo Job",
            triggerPartyJobs: "Trigger Party Job",
            soloJobMoneyRate: "Solo Job Money Rate",
            soloJobExpRate: "Solo Job Exp Rate",
            soloJobItemDropRate: "Solo Job Item Drop Rate",
            soloJobFrequency: "Solo Job Frequency",
            changeName: "Change Name",
            proportionateExplanation:
                "Guard's rates are proportionate to your gaining rates. With upgrades these rates will be improved.",
            info: "Info",
            statistics: "Statistics",
            property: "Property",
            management: "Management",
            guard2Explanation:
                "Your guard will work every 5 mins. Guard will consume 5 energy for property checking, and for management 2 energy per active property. \n\nGuard will deposit money to selected properties until the selected amount. Also guard will gain more experience for each active task.",
            depositToProperties: "Deposit to Properties",
        },
        updating: {
            updatingApp: "Updating App",
            downloadingNewVersion:
                "Downloading new version... App will restart after installation",
            updateFailed: "Update failed",
            updateAvailable: "Update available",
            wouldYouLikeToUpdate: "Would you like to update?",
            updateNow: "Update Now",
        },
        gameKeys: {
            hp: "HP",
            energy: "Energy",
            str: "STR",
            dex: "DEX",
            int: "INT",
            char: "CHAR",
            dmg: "DMG",
            def: "DEF",
            pre: "PRE",
            xp: "XP",
        },
        auth: {
            registration: "Registration",
            login: "Login",
            username: "Username",
            email: "Email",
            emailOrUsername: "Email or Username",
            rememberMe: "Remember Me?",
            password: "Password",
            confirmPassword: "Confirm Password",
            usernameTooShort: "Username must be at least 3 characters long",
            invalidEmail: "Invalid email address",
            passwordTooShort: "Password must be at least 6 characters long",
            passwordsDoNotMatch: "Passwords do not match",
            register: "Register",
            forgotPassword: "Forgot Password?",
            alreadyHaveAccount: "Already have an account? ",
            registerModalWarning:
                "To save your progress, please register. Otherwise, you may not be able to login from another device.",
            reset: "Reset",
            resetPassword: "Reset Password",
        },
        home: {
            jobs: "Jobs",
            inventory: "Inventory",
            chat: "Chat",
            play: "Play",
            pause: "Pause",
            next: "Next",
        },
        main: {
            inventory: "Inventory",
            selectedItemWillBeDeleted:
                "Selected item will be deleted, are you sure?",
        },
        common: {
            difficulty: "Difficulty",
            risk: "Risk",
            start: "Start",
            change: "Change",
            selected: "Selected",
            takeAll: "Take All",
            improve: "Improve",
            improvements: "Improvements",
            requiredLevel: "Required Level",
            assign: "Assign",
            unassign: "Unassign",
            check: "Check",
            craft: "Craft",
            repair: "Repair",
            mine: "Mine",
            later: "Later",
            subProperties: "Sub Properties",
            progress: "Progress",
            shadowCoin: "Shadow Coin",
            success: "Success",
            failed: "Failed",
            duration: "Duration",
            min: "Min.",
            lastActivity: "Last activity",
            status: "Status",
            active: "Active",
            idle: "Idle",
            online: "Online",
            equip: "Equip",
            unEquip: "Unequip",
            use: "Use",
            quantity: "Quantity",
            imageTooBig: "Image too big!",
            maxImageSize: "Maximum image size is ",
            money: "Money",
            experience: "Experience",
            stats: "Stats",
            choose: "Choose",
            level: "Level",
            grade: "Grade",
            energy: "Energy",
            strength: "Strength",
            dexterity: "Dexterity",
            intelligence: "Intelligence",
            charisma: "Charisma",
            location: "Location",
            quality: "Quality",
            send: "Send",
            gameKeys: {
                damage: "Damage",
                defence: "Defence",
                health: "Health",
                max_health: "Max HP",
                energy: "Energy",
                max_energy: "Max Energy",
                health_regen: "HP Regen",
                energy_regen: "Energy Regen",
                required_level: "Level",
                durability: "Durability",
                level: "Level",
                strength: "Strength",
                dexterity: "Dexterity",
                intelligence: "Intelligence",
                charisma: "Charisma",
                money: "Money",
                item_drop_chance: "Item Drop",
                money_gain: "Money Gain",
                upgrade_chance: "UPG Chance",
                critical_chance: "CRIT Chance",
                experience_gain: "XP Gain",
            },
            gameKeysMultiplier: {
                item_drop_chance: 100,
                money_gain: 100,
                upgrade_chance: 100,
                critical_chance: 100,
                experience_gain: 100,
            },
            gameKeysPostText: {
                item_drop_chance: "%",
                money_gain: "%",
                upgrade_chance: "%",
                critical_chance: "%",
                experience_gain: "%",
            },
            qualities: {
                0: "Common",
                1: "Rare",
                2: "Epic",
                3: "Legendary",
            },
            requirements: "Requirements",
            traits: "Traits",
            classNames: {
                1: "Gangster",
                2: "Detective",
                3: "Businessman",
            },
            error: "Error",
            somethingWentWrong: "Something went wrong",
            all: "All",
            itemTypeNames: {
                [ItemType.Consumable]: "Consumables",
                [ItemType.Goods]: "Goods",
                [ItemType.Weapon]: "Weapons",
                [ItemType.Armor]: "Armors",
                [ItemType.Material]: "Materials",
                [ItemType.Helmet]: "Helmets",
            },
            itemTypeName: {
                [ItemType.Consumable]: "Consumable",
                [ItemType.Goods]: "Goods",
                [ItemType.Weapon]: "Weapon",
                [ItemType.Armor]: "Armor",
                [ItemType.Material]: "Material",
                [ItemType.Helmet]: "Helmet",
            },
            propertyTypeNames: {
                [PropertyType.Flat]: "Flat",
                [PropertyType.Shop]: "Shop",
                [PropertyType.Production]: "Production",
                [PropertyType.Casino]: "Casino",
                [PropertyType.WeaponDealer]: "Weapon Dealer",
                [PropertyType.Garage]: "Garage",
            },
            upgrade: "Upgrade",
            delete: "Delete",
            disassemble: "Disassemble",
            warning: "Warning",
            close: "Close",
            confirm: "Confirm",
            select: "Select",
            selectItem: "Select Item",
            price: "Price",
            enterPrice: "Enter Price",
            amount: "Amount",
            enterAmount: "Enter Amount",
            cancel: "Cancel",
            join: "Join",
            travel: "Travel",
            prestige: "Prestige",
            buy: "Buy",
            remove: "Remove",
            sell: "Sell",
            onSale: "On Sale",
            closed: "Closed",
            owned: "Owned",
            cost: "Cost",
            bonus: "Bonus",
            depositMoney: "Deposit Money",
            withdrawMoney: "Withdraw Money",
            deposit: "Deposit",
            withdraw: "Withdraw",
            take: "Take",
            pause: "Pause",
            continue: "Continue",
            accept: "Accept",
            refuse: "Refuse",
            kick: "Kick",
            leave: "Leave",
            bountyPointCost: "Bounty Point Cost",
            result: "Result",
            free: "Free",
            reroll: "Reroll",

            // Global game values
            dmg: "DMG",
            def: "DEF",
            lvl: "LVL",
            pre: "PRE", // Prestige
            xp: "XP",
        },
        selectClass: {
            timeToChooseClass: "Time to choose your class!",
            changeYourClass: "Change Your Class",
            jobEarningsRate: "Job earnings rate: ",
            riskRates: {
                3: "Low",
                2: "Medium",
                1: "High",
            },
            mainStats: "Main Stats: ",
            classChangeWarning:
                "Are you sure you want to change your class? After changing, your stats will be redistributed according to the class you choose and you will not be able to change your class again for a certain period.",
        },
        jobs: {
            title: "Jobs",
            lastRun: "Last Run",
            specialRunRewards: {
                gained_money: "Gained Money",
                gained_experience: "Gained Experience",
                gained_shadow_coin: "Gained Shadow Coin",
                gained_strength: "Gained Strength",
                gained_dexterity: "Gained Dexterity",
                gained_intelligence: "Gained Intelligence",
                gained_charisma: "Gained Charisma",
                taken_damage: "Taken Damage",
            },
            itemLoot: "Item Loot",
            result: "Result",
            success: "Success",
            failed: "Failed",
            completedAt: "Completed at",
            doJob: "Do Job",
            selectJob: "Select Job",
            unSelectJob: "Unselect",
            youHaveGained: "You have gained ",
            youNeedLevelToCompleteThisJob:
                "You need level {level} to complete this job",
            youNeedLevelToStartThisMission:
                "You need level {level} to start this mission",
            soloJobs: "Solo Jobs",
            partyJobs: "Party Jobs",
            specialRun: "Special Run",
            missions: "Missions",
            requiredCrew: "Required Crew",
            createParty: "Create Party",
            joinParty: "Join a Party",
            joinTheParty: "Join the Party",
            crew: "Crew",
            noParty: "No parties found. You can create a party by pressing +",
            youAreKickedFromTheParty: "You have been kicked from the party",
            thisPartyIsFull: "This party is full",
            leaveParty: "Leave Party",
            requirements: "Requirements",
            partyStats: "Party Stats",
            prepare: "Prepare",
            start: "Start",
            preparingOnGoing: "Preparation in progress",
            ready: "Ready",
            rewards: "Rewards",
            onCooldown: "On Cooldown",
            waitingForCrew: "Waiting for Crew",
            readyUp: "Ready Up",
            completed: "Completed",
            waiting: "Waiting...",
            cannotKickOthers: "You cannot kick other members.",
            partyDismissed: "Party has been dismissed.",
            waitingForLeader: "Waiting for leader...",
            jobOnCooldownGeneric: "Job is on cooldown.",
            dismissParty: "Dismiss Party",
            loot: "Loot",
            totalRequiredDamage: "Total required damage to inflict",
            possibleIncomingDamage: "Possible incoming damage",
            lastMission: "Last Mission",
            startMission: "Start Mission",
            missionOutcome: "Mission Outcome",
            activeMission: "Active Mission",
            damageDealt: "Damage Dealt",
            damageReceived: "Damage Received",
        },
        chat: {
            daysAgo: "days ago",
            hoursAgo: "hours ago",
            minutesAgo: "minutes ago",
            secondsAgo: "seconds ago",
            gameChat: "Game Chat",
            globalChat: "Global Chat",
            gangChat: "Gang Chat",
            message: "Message...",
            messages: "Messages",
            chat: "Chat",
        },
        drawer: {
            joinUs: "Join Us",
            tutorials: "Tutorials",
            settings: "Settings",
            support: "Support",
            game: "Game",
            editProfile: "Edit Profile",
            gangs: "Gangs",
            encounters: "Encounters",
            fights: "Fights",
            confinedPeople: "Confined",
            ranking: "Ranking",
            districts: "Districts",
            character: "Character",
            boosts: "Shadow Shop",
            buyCoins: "Buy S-coin",
            cosmetics: "Cosmetics",
            logout: "Logout",
            moderationPanel: "Moderation Panel",
            faq: "FAQ",
            itemList: "Item List",
            guards: "Guards",
            announcements: "Updates",
        },
        editProfile: {
            header: "Profile",
            editPicture: "Edit Picture",
            accountInformation: "Account Information",
            saveChanges: "Save Changes",
            changePassword: "Change Password",
            currentPassword: "Current Password",
            newPassword: "New Password",
            typeYourPassword: "Type your password",
            deleteAccount: "Delete Account",
            yourAccountWillBeDeleted:
                "Your account will be deleted, are you sure?",
        },
        confinedPeople: {
            header: "Confined",
            prison: "Prison",
            hospital: "Hospital",
            ransomPrice: "Ransom Price",
            treatmentCosts: "Treatment Cost",
            requiredEnergy: "Required Energy",
            rescue: "Rescue",
            remainingTime: "Remaining Time",
        },
        propertyDetails: {
            building: "Building",
            saleItems: "Items for Sale",
            inventory: "Inventory",
            propertyDetails: "Property Details",
            deleteProperty: "Delete Property",
            writeDeleteToDelete: "Write 'Delete' to delete",
            changeLocation: "Change Location",
            changeLocationCost: "Changing location costs {cost}",
            chooseNewLocation: "Choose New Location",
            chooseNewBuilding: "Choose New Building",
            buyOrder: "Buy Order",
            auctionOrder: "Start Auction",
            visitors: "Visitors",
            upgrades: "Upgrades",
            workshop: "Workshop",
            productionList: "Production List",
            gamble: "Gamble",
            garage: "Garage",
            removeFromSale: "Remove from Sale",
            removeFromSaleDetails: "Your property sale will be cancelled",

            putOnSale: "Put on Sale",
            putOnSaleDetails:
                "Your property will be available for other players to buy",
            buy: "Buy",
            numberOfVisits: "Number of Visits",
            leaveMessage: "Leave a Message",
            noItemsOnSale: "No items on sale",
            listedForSale: "Listed for Sale",
            salePrice: "Sale Price",
            owner: "Owner",
            maintenanceCost: "Maintenance Cost",
            usageFee: "Usage Fee",
            conditionHealth: "Condition (Health)",
            changeName: "Change Name",
            changeNameCost: "Changing name costs {cost}",
            moneyInProperty: "Money in Property",
            productionCost: "Production Cost",
            buyProperty: "Buy Property",
            minimumAuctionEntryPrice: "Minimum Auction Entry Price",
            auctionStartFee: "Auction Starting Fee",
            buyPropertySure: "Are you sure you want to buy this property?",
            needsMaintenance: "Needs Maintenance",
            maintenance: "Maintenance",
            setUsageFee: "Set Usage Fee",
            usageFeeDescription:
                "Usage fee is the amount of money you will receive for the propertionate to the crafting cost.",
            batchSell: "Batch Sell",
            batchDisassemble: "Batch Disassemble",
            chooseAll: "Choose All",
            sellAll: "Sell All",
            bid: "Bid",
        },
        propertyCasino: {
            blackjack: "Blackjack",
            blackjackShortExplanation:
                "Blackjack is a classic card game where your goal is to get 21 points or be closer to it than the dealer without exceeding it.",
            basicRules: "Basic Rules",
            blackjackRules: [
                "Player & Dealer get 2 cards.",
                "Player can 'Hit' (draw more cards).",
                "Exceed 21 = Bust (Lose).",
                "Dealer Hits until 17+.",
                "Ace = 1 or 11. Face Cards/10s = 10.",
                "Highest score (<= 21) wins.",
            ],
            play: "Play",
            placeYourBet: "Place Your Bet",
            minMaxRatesAre: "Minimum bet: {min}$ \n\nMaximum bet: {max}$",
            pleaseChooseCorrectBetAmount: "Please choose a valid bet amount",
            hit: "Hit",
            stand: "Stand",
            betTitles: {
                [BetStatus.CONTINUE]: "Your bet",
                [BetStatus.LOSE]: "You Lost...",
                [BetStatus.DEALER_BUST]: "You WON!",
                [BetStatus.WIN]: "You WON!",
                [BetStatus.PUSH]: "You got your money back",
            },
            playAgain: "Play Again",
        },
        propertyModal: {
            chooseProperty: "Choose Property",
            propertyName: "Property Name",
            enterName: "Enter Name",
            buyProperty: "Buy Property",
        },
        encounters: {
            title: "Encounters",
            peopleYouHaveMet: "People You Have Met",
            search: "Search",
            investigate: "Investigate",
            location: "Location",
            encountered: "Encountered",
            investigateCost: `Investigating using a detective has a higher chance of success, but costs {cost}$. Continue?`,
            attack: "Attack",
            levelDiff:
                "Since the difference between the level of the person you want to attack and your level is too high, you will get bounty points after the attack. Are you sure?",
            removeAll: "Remove All",
            removeAllDescription: `Remove all cost {all_cost} S-coin, and removing one costs {one_cost} S-coin. Long press to remove.`,
        },
        playerProfile: {
            prestige: "Prestige",
            rank: "Rank",
            statistics: "Statistics",
            stats: {
                jobs: "Jobs",
                party_jobs: "Party Jobs",
                total_attacks: "Total Attacks",
                total_received_attacks: "Total Received Attacks",
                total_won_fights: "Total Won Fights",
                total_lost_fights: "Total Lost Fights",
                money_gain: "Money Gained",
                party_money_gain: "Party Money Gained",
                gambling_gain: "Gambling Gains",
                item_upgrade_amount: "Items Upgraded",
                missions: "Missions",
                prison: "Prison",
                hospital: "Hospital",
                experience_gain: "Experience Gained",
                energy_spent: "Energy Spent",
            },
            playerBlocked:
                "Player Blocked, you won't to see their messages in chat anymore",
            reportNickName: "Report Nickname",
            reportMessage: "Report Message",
            reportProfileImage: "Report Profile Image",
            reportGangImage: "Report Gang Image",
            blockPlayer: "Block Player",
        },
        settings: {
            title: "Settings",
            general: "General",
            language: "Language",
            gameplay: "Gameplay",
            autoEatFood: "Auto-Eat Food",
            passiveGrindingMode: "Passive Grinding Mode",
            jobInfo:
                "In passive grinding mode your character will automatically grind, will do solo jobs every minute x times.\n\nParty jobs will trigger once per 3 minutes.\n\nPassive grinding mode is active for 1h from the last time you were online.",
            eatBelow: "Eat when energy falls below {energy}%",
            healBelow: "Heal when health falls below {health}%",
            jobPerMinute: "Solo Jobs Per Minute",
            autoHeal: "Auto-Heal",
            on: "On",
            off: "Off",

            privacy: "Privacy",
            privacyPolicy: "Privacy Policy",
            blockedUsers: "Blocked Users",
            eula: "EULA",
            login: "Login",
            logout: "Logout",
            languages: {
                en: "English",
                tr: "Turkish",
            },
            country: "Country",
        },
        districts: {
            title: "Districts",
            streetBonus: "This street has",
            economic_bonus: "Trade Efficiency",
            money_gain_bonus: "Money Gain",
            stat_gain_bonus: "Stat Gain",
            preparationPhase: "Preparation Phase",
            fightPhase: "Fight Phase",
            owningPhase: "Ownership Phase",
            contribution: "Contribution",
            preparationPhaseDescription:
                "Select the street your gang will fight for.",
            fightPhaseDescription:
                "Battle for the district. The gang that sheds the most blood claims victory.",
            owningPhaseDescription:
                "Every gang owns one street and gather tributes.",
            endsIn: "Ends In",
        },
        character: {
            statList: {
                0: "Total Damage",
                1: "Damage from Items",
                2: "Stat Damage Contribution",

                3: "Total Defence",
                4: "Defence from Items",
                5: "Stat Defence Contribution",
            },
            classes: {
                1: "Gangster",
                2: "Detective",
                3: "Businessman",
            },
            bonusList: {
                trade_efficiency: "Trade Efficiency",
                production_efficiency: "Production Efficiency",
                max_health: "Max HP",
                max_energy: "Max Energy",
                health_regen: "HP Regen",
                energy_regen: "Energy Regen",
                money_gain: "Money Gain Bonus",
                stat_gain: "Stat Gain Bonus",
                upgrade_chance: "Upgrade Chance Bonus",
                critical_chance: "Critical Chance Bonus",
                experience_gain: "Experience Gain Bonus",
                prison_avoid_chance: "Prison Avoid Chance Bonus",
                item_drop_chance: "Item Drop Chance Bonus",
                hospital_avoid_chance: "Hospital Avoid Chance Bonus",
            },
            bonusListEndCharacter: {
                trade_efficiency: "%",
                production_efficiency: "%",
                money_gain: "%",
                stat_gain: "%",
                upgrade_chance: "%",
                critical_chance: "%",
                experience_gain: "%",
                prison_avoid_chance: "%",
                item_drop_chance: "%",
                hospital_avoid_chance: "%",
            },
            bonusListStartCharacter: {
                trade_efficiency: "+",
                production_efficiency: "+",
                money_gain: "+",
                stat_gain: "+",
                upgrade_chance: "+",
                critical_chance: "+",
                experience_gain: "+",
                prison_avoid_chance: "+",
                item_drop_chance: "+",
                hospital_avoid_chance: "+",
            },
            character: "Character",
            presets: "Presets",
            bonuses: "Bonuses",
            statistics: "Statistics",
            changeClass: "Change Class",
        },
        ranking: {
            title: "Ranking",
            tabs: ["Prestige", "Level", "Guard Rank"],
        },
        questModal: {
            title: "Quests",
            claimRewards: "Claim Rewards",
            rewards: "Rewards",
            story: "Story",
            daily: "Daily",
            noQuest:
                "No quests found. New quests will appear here when available",
            nextResetIn: "Next Reset In",
        },
        gangs: {
            title: "Gangs",
            createGang: "Create Gang",
            gangCreationCost: "Creating a gang costs: {cost}",
            gangName: "Gang Name",
            roleNames: {
                [GangMemberRoles.JOIN_REQUEST]: "Join Request",
                [GangMemberRoles.MEMBER]: "Member",
                [GangMemberRoles.OWNER]: "Leader",
            },
            totalPrestige: "Total Prestige",
            bountyPoints: "Bounty Points",
            gangs: "Gangs",
            upgrades: "Upgrades",
            donateMoney: "Donate Money",
            changeGangImage: "Change Gang Image",
            changeGangLeader: "Change Gang Leader",
            gangLeaderWillBeChanged:
                "Gang leader will be changed, are you sure?",
        },
        fights: {
            winnerOfFight: "{name} won the fight!",
            you: "You",
            youLostTheFight: "You lost the fight!",
            summary: "Summary",
            defenderDodged:
                "Both parties decided not to fight, maybe next time!",
        },
        boosts: {
            title: "Shadow Shop",
            boosts: "Boosts",
            packs: "Packs",
            myBoosts: "My Boosts",
            hours: "hours",
            youWillActivateBoostAreYouSure:
                "You will activate this boost. Are you sure?",
            youWillBuyThisPackAreYouSure:
                "You will buy this pack. Are you sure?",
            reminder: "Reminder",
            gainScoins: "Gain S-coins",
        },
        upgradeItem: {
            title: "Upgrade",
            successChance: "Success Chance",
            chance: "Chance",
            safeUpgrade: "Safe Upgrade",
            safeUpgradeDescription:
                "When upgrading without safety, there's a risk that your item will be destroyed. Using safe upgrade costs more but guarantees your item will remain intact even if the upgrade fails.",
            reroll: "Reroll",
            rerollDescription:
                "Rerolling an item will change its sub-properties. Changes are random and irreversible. Are you sure?",
        },
        support: {
            title: "Support",
            createTicket: "Create Ticket",
            newTicket: "New Ticket",
            chooseTopic: "Choose a Topic",
            topics: [
                {
                    id: 1,
                    name: "Bug",
                    explanation: "(Something is not working as expected)",
                },
                {
                    id: 2,
                    name: "Idea",
                    explanation: "(Suggestion or feedback)",
                },
                {
                    id: 3,
                    name: "Payment",
                    explanation: "(Payment issues)",
                },
                {
                    id: 4,
                    name: "Account Issues",
                    explanation: "(Login/Profile problems)",
                },
                {
                    id: 5,
                    name: "Other",
                    explanation: "(Something else?)",
                },
            ],
            yourMessage: "Your Message",
            writeMessage: "Write a message",
            min30Characters: "Min 30 characters",
            upTo3Files: "You can upload up to 3 photos or videos",
            changeStatusTo: "Change to",
            ticketStatus: {
                [TicketStatus.Closed]: "Closed",
                [TicketStatus.Pending]: "Pending",
                [TicketStatus.Answered]: "Answered",
            },
        },
        moderationPanel: {
            title: "Moderation",
        },
        copilot: {
            next: "Next",
            back: "Back",
            finish: "Finish",
            skip: "Skip",
            home: {
                1: "Welcome to Shadow Streets! This is your current street. Tap on buildings to interact with different locations and uncover secrets.",
                2: "Follow your Quests here! They are essential for learning the game mechanics, progressing the story, and earning valuable rewards.",
                3: "Open the side menu here to explore more game features, manage your character, view rankings, and access settings.",
                4: "Access the Jobs screen here. Complete jobs to earn money, gain experience, and find new opportunities.",
                5: "Manage your Inventory here. Equip weapons and armor, use items, and see what valuable goods you've collected.",
                6: "Connect with other players in the Chat. Discuss strategies, join forces, or just hang out in the city.",
            },
        },
        buyShadowCoin: {
            title: "Buy S-Coin",
            productFetchFailed:
                "Products couldn't be fetched, please try again later.",
        },
        cosmetics: {
            title: "Cosmetics",
            tabs: ["Avatar Frames", "My Cosmetics"],
            youWillBuyThisFrame:
                "You will buy this frame for {price} S-coins, are you sure?",
        },
        itemList: {
            title: "Item List",
        },
    },
});

export function getDeviceLanguage() {
    return strings.getLanguage();
}

export default strings;
