export const SILENT_AUTH = "SILENT_AUTH";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";

export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";

export const RESET_STATES = "RESET_STATES";

export const GET_USER_BONUSES = "GET_USER_BONUSES";
export const SET_USER_BONUSES = "SET_USER_BONUSES";

export const SET_USER_LOADED = "SET_USER_LOADED";

export const SET_BLOCKED_USERS = "SET_BLOCKED_USERS";

export const SAVE_USER_MARKETING_INFO = "SAVE_USER_MARKETING_INFO";

export const GET_BOT_RESTRICTION = "GET_BOT_RESTRICTION";
export const SET_BOT_RESTRICTION = "SET_BOT_RESTRICTION";

export const GET_USER_SETTINGS = "GET_USER_SETTINGS";
export const SET_USER_SETTINGS = "SET_USER_SETTINGS";

export const SET_JOB_CAPTCHA_ACTIVE = "SET_JOB_CAPTCHA_ACTIVE";

export const SET_PARTY_JOB_CAPTCHA_ACTIVE = "SET_PARTY_JOB_CAPTCHA_ACTIVE";

export const SET_FAVORITE_ITEMS = "SET_FAVORITE_ITEMS";
