export const GET_MY_BOOSTS_REQUEST = "GET_MY_BOOSTS_REQUEST";
export const GET_MY_BOOSTS_SUCCESS = "GET_MY_BOOSTS_SUCCESS";
export const GET_MY_BOOSTS_FAILURE = "GET_MY_BOOSTS_FAILURE";

export const GET_PACKS = "GET_PACKS";
export const SET_PACKS = "SET_PACKS";
