export const SET_CURRENT_CHAT_INDEX = "SET_CURRENT_CHAT_INDEX";

export const SET_GAME_CHAT_MESSAGES_READ = "SET_GAME_CHAT_MESSAGES_READ";
export const SET_GAME_CHAT_MESSAGES = "SET_GAME_CHAT_MESSAGES";
export const SET_GANG_CHAT_MESSAGES_READ = "SET_GANG_CHAT_MESSAGES_READ";
export const SET_GANG_CHAT_MESSAGES = "SET_GANG_CHAT_MESSAGES";

export const ADD_CHAT_MESSAGE = "ADD_CHAT_MESSAGE";

export const SET_CHAT_LOADING = "SET_CHAT_LOADING";
