export const GET_GAME_CONFIG = "GET_GAME_CONFIG";
export const SET_GAME_CONFIG = "SET_GAME_CONFIG";

export const GET_GAME_STREETS = "GET_GAME_STREETS";
export const SET_GAME_STREETS = "SET_GAME_STREETS";

export const GET_GAME_ITEMS = "GET_GAME_ITEMS";
export const SET_GAME_ITEMS = "SET_GAME_ITEMS";

export const GET_GAME_PROPERTY_UPGRADES = "GET_GAME_PROPERTY_UPGRADES";
export const SET_GAME_PROPERTY_UPGRADES = "SET_GAME_PROPERTY_UPGRADES";

export const GET_GAME_GANG_UPGRADES = "GET_GAME_GANG_UPGRADES";
export const SET_GAME_GANG_UPGRADES = "SET_GAME_GANG_UPGRADES";

export const GET_GAME_MISSIONS = "GET_GAME_MISSIONS";
export const SET_GAME_MISSIONS = "SET_GAME_MISSIONS";
