export const GET_GROUP_FIGHTS = "GET_GROUP_FIGHTS";
export const SET_GROUP_FIGHTS = "SET_GROUP_FIGHTS";

export const GET_GROUP_FIGHT_DETAILS = "GET_GROUP_FIGHT_DETAILS";
export const SET_GROUP_FIGHT_DETAILS = "SET_GROUP_FIGHT_DETAILS";

export const JOIN_GROUP_FIGHT = "JOIN_GROUP_FIGHT";

export const LEAVE_GROUP_FIGHT = "LEAVE_GROUP_FIGHT";

export const GET_ACTIVE_FIGHTS_IN_CURRENT_DISTRICT =
    "GET_ACTIVE_FIGHTS_IN_CURRENT_DISTRICT";
export const SET_ACTIVE_FIGHTS_IN_CURRENT_DISTRICT =
    "SET_ACTIVE_FIGHTS_IN_CURRENT_DISTRICT";
