export const ADD_ITEM_TO_PRODUCTION = "ADD_ITEM_TO_PRODUCTION";

export const GET_PROPERTY_ITEM_PRODUCTION_LIST =
    "GET_PROPERTY_ITEM_PRODUCTION_LIST";
export const SET_PROPERTY_ITEM_PRODUCTION_LIST =
    "SET_PROPERTY_ITEM_PRODUCTION_LIST";

export const TAKE_PRODUCED_ITEM_FROM_PROPERTY =
    "TAKE_PRODUCED_ITEM_FROM_PROPERTY";

export const TAKE_ALL_PRODUCED_ITEMS_FROM_PROPERTY =
    "TAKE_ALL_PRODUCED_ITEMS_FROM_PROPERTY";

export const STOP_ITEM_PRODUCTION_IN_PROPERTY =
    "STOP_ITEM_PRODUCTION_IN_PROPERTY";

export const REMOVE_ITEM_FROM_PRODUCTION = "REMOVE_ITEM_FROM_PRODUCTION";
